### PR TITLE
[FEAT] Add additional recipe maintainers

### PR DESCRIPTION
**Pull request by FedericoGarza**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FedericoGarza** [comment]
cc @cchallu

**Comment by FedericoGarza** [comment]
hi @sugatoray! Have you had a chance to review the pull request? :)

**Comment by sugatoray** [comment]
@FedericoGarza Not yet. I will take a look at it. It doesn't seem like it is failing the build process. Is there anything else that is concerning?

**Comment by FedericoGarza** [comment]
> The only noticeable change is adding another maintainer. Right?

Yes, exactly @sugatoray. 

Could you merge the PR? I still need permission xD. Thank you!

**Pull request merged**
